# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 02d310c39315f27f955e75b89fed48a96e604819c76d54c142830ac4f34861119b5f7cc3c498758932e8de431596f50992859ab1a7a0b82e02bbff80133bd6d8

test:
  secret_key_base: b07faaca4fb5a8cc53c5d9fc1dce6156c64dd071d53f80d7143d507f2a6ef43cfaae2399e5d2ce9a2ba1db10daf44bb97bd951bdc6e21bea5d5eb54da2c5116a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
